-- Seed data for rewards (30 Items)

INSERT IGNORE INTO `rewards` (`id`, `event_id`, `name`, `description`, `points_price`, `image_path`, `stock`) VALUES
(1, 1, 'University Classic T-Shirt', 'High-quality cotton t-shirt featuring the university crest.', 150, NULL, 100),
(2, 2, 'Premium Coffee Mug', 'Ceramic coffee mug, perfect for early morning classes.', 50, NULL, 200),
(3, 3, 'Leather-bound Notebook', 'A premium lined notebook with a hard cover.', 75, NULL, 50),
(4, 4, 'VIP Event Pass', 'Exclusive front-row seat to the next major campus event.', 500, NULL, 10),
(5, 5, 'Cafeteria Lunch Voucher', 'Valid for one free combo meal at the main dining hall.', 100, NULL, 150),
(6, 6, 'University Hoodie', 'Warm, comfortable hoodie in university colors.', 300, NULL, 50),
(7, 7, 'Campus Bookstore $10 Gift Card', 'Can be used for any purchase at the campus bookstore.', 120, NULL, -1),
(8, 8, 'Campus Bookstore $25 Gift Card', 'Can be used for any purchase at the campus bookstore.', 250, NULL, -1),
(9, 9, 'Alumni Association Lanyard', 'Durable lanyard with a detachable keychain.', 25, NULL, 500),
(10, 10, 'Stainless Steel Water Bottle', 'Insulated 32oz water bottle with engraved logo.', 150, NULL, 75),
(11, 11, 'Wireless Earbuds', 'Bluetooth earbuds with a charging case.', 400, NULL, 20),
(12, 12, 'Portable Power Bank', '10,000mAh power bank to keep your devices charged.', 250, NULL, 30),
(13, 13, 'University Tote Bag', 'Eco-friendly canvas tote bag.', 40, NULL, 300),
(14, 14, 'Limited Edition Enamel Pin', 'Collector''s pin for the current academic year.', 30, NULL, 200),
(15, 15, 'Executive Pen Set', 'Two smooth-writing pens in a presentation box.', 80, NULL, 100),
(16, 16, 'Library Printing Credits (100 Pages)', 'Adds 100 pages to your campus printing account.', 50, NULL, -1),
(17, 17, 'Priority Class Registration', 'Get access to class registration 1 hour early.', 1000, NULL, 5),
(18, 18, 'Campus Parking Pass (1 Week)', 'Free parking in any student lot for one week.', 200, NULL, 25),
(19, 19, 'Gym Day Pass', 'One free day access to the campus recreation center.', 30, NULL, -1),
(20, 20, 'Intramural Sports Team Fee Waiver', 'Waives the registration fee for one intramural team.', 150, NULL, 20),
(21, 21, 'Laptop Sticker Pack', 'A pack of 5 die-cut university themed stickers.', 15, NULL, 500),
(22, 22, 'Department Seminar Lunch Invitation', 'Join the faculty for a catered lunch after a seminar.', 200, NULL, 15),
(23, 23, 'Graduation VIP Seating (2 Tickets)', 'Reserved premium seating for family at graduation.', 800, NULL, 10),
(24, 24, 'Resume Review Session', '1-on-1 resume review with the Career Services Director.', 150, NULL, 20),
(25, 25, 'Professional Headshot Session', 'A 15-minute photo session with the campus photographer.', 250, NULL, 30),
(26, 26, 'University Throw Blanket', 'Soft fleece blanket featuring the mascot.', 180, NULL, 40),
(27, 27, 'Reusable Coffee Cup', 'Eco-friendly bamboo coffee cup.', 60, NULL, 100),
(28, 28, 'Campus Tech Support Jump-the-Line', 'Priority service ticket for the IT Helpdesk.', 100, NULL, -1),
(29, 1, 'Guest Lecture Backstage Pass', 'Meet the speaker before a major campus guest lecture.', 400, NULL, 5),
(30, 2, 'Custom Graduation Stole', 'A personalized graduation stole embroidered with your name.', 600, NULL, 25);