// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/event-listing": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/event/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/event-management": {
    params: {};
  };
  "/participant-management": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/event-listing" | "/login" | "/register" | "/event/:id" | "/dashboard" | "/event-management" | "/participant-management";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/public/eventListing.tsx": {
    id: "routes/public/eventListing";
    page: "/event-listing";
  };
  "routes/public/login.tsx": {
    id: "routes/public/login";
    page: "/login";
  };
  "routes/public/register.tsx": {
    id: "routes/public/register";
    page: "/register";
  };
  "routes/public/event.$id.tsx": {
    id: "routes/public/event.$id";
    page: "/event/:id";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/eventManagement.tsx": {
    id: "routes/admin/eventManagement";
    page: "/event-management";
  };
  "routes/admin/participantManagement.tsx": {
    id: "routes/admin/participantManagement";
    page: "/participant-management";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/public/home": typeof import("./app/routes/public/home.tsx");
  "routes/public/about": typeof import("./app/routes/public/about.tsx");
  "routes/public/eventListing": typeof import("./app/routes/public/eventListing.tsx");
  "routes/public/login": typeof import("./app/routes/public/login.tsx");
  "routes/public/register": typeof import("./app/routes/public/register.tsx");
  "routes/public/event.$id": typeof import("./app/routes/public/event.$id.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/eventManagement": typeof import("./app/routes/admin/eventManagement.tsx");
  "routes/admin/participantManagement": typeof import("./app/routes/admin/participantManagement.tsx");
};