// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/eventListing": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/eventManagement": {
    params: {};
  };
  "/participantManagement": {
    params: {};
  };
  "/eventRegistration": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/eventListing" | "/login" | "/register" | "/dashboard" | "/eventManagement" | "/participantManagement" | "/eventRegistration";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/public/eventListing.tsx": {
    id: "routes/public/eventListing";
    page: "/eventListing";
  };
  "routes/public/login.tsx": {
    id: "routes/public/login";
    page: "/login";
  };
  "routes/public/register.tsx": {
    id: "routes/public/register";
    page: "/register";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/eventManagement.tsx": {
    id: "routes/admin/eventManagement";
    page: "/eventManagement";
  };
  "routes/admin/participantManagement.tsx": {
    id: "routes/admin/participantManagement";
    page: "/participantManagement";
  };
  "routes/student/eventRegistration.tsx": {
    id: "routes/student/eventRegistration";
    page: "/eventRegistration";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/public/home": typeof import("./app/routes/public/home.tsx");
  "routes/public/about": typeof import("./app/routes/public/about.tsx");
  "routes/public/eventListing": typeof import("./app/routes/public/eventListing.tsx");
  "routes/public/login": typeof import("./app/routes/public/login.tsx");
  "routes/public/register": typeof import("./app/routes/public/register.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/eventManagement": typeof import("./app/routes/admin/eventManagement.tsx");
  "routes/admin/participantManagement": typeof import("./app/routes/admin/participantManagement.tsx");
  "routes/student/eventRegistration": typeof import("./app/routes/student/eventRegistration.tsx");
};