CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description LONGTEXT,
    event_start_date DATETIME NOT NULL,
    event_start_time TIME NOT NULL,
    event_end_date DATETIME NOT NULL,
    event_end_time TIME NOT NULL,
    location VARCHAR(255),
    department VARCHAR(255),
    organizer_id INT NOT NULL,
    max_participants INT,
    current_participants INT DEFAULT 0,
    status ENUM('pending', 'approved', 'rejected', 'ongoing', 'completed', 'cancelled') DEFAULT 'pending',
    image_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (organizer_id) REFERENCES organizers(id) ON DELETE CASCADE,
    INDEX idx_organizer_id (organizer_id),
    INDEX idx_event_start_date (event_start_date),
    INDEX idx_status (status)
);